version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    volumes:
      - ./docker/realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
      - "-Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    ports:
      - "8080:8080"